#
# My_testing_GitHub_Action
#

name: HelloAction

on:
  push:
    branches: 
      - master

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Python script
      run: python hello.py
