#
# My_testing_GitHub_Action
#

name: HelloAction

on:
  push:
    branches: 
      - master

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Messag—É
      run: hello.py
