#
# My_testing_GitHub_Action_Assignment 2
#

name: Building_and_Testing

on:
  push:
    branches: 
      - master

jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run operation script
      run: basic_operation.py

  second_job:
    runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run testing script
      run: basic_test.py
